### ISSUE TITLE
First Design

### ISSUE THREAD

**Issue by mauriciozanettisalomao** [mauriciozanettisalomao/go-transaction-service#1]
## Description
Based on the following requirements, it is necessary to design a solution, including resources, to be a production-ready solution.

Model (transaction) - List and Create endpoints:
* ID
* the origin where the user started this transaction (e.g. “desktop-web”, “mobile-android”,
“mobile-ios”...)
* the ID of the user that made that transaction
* the monetary amount transaction
* the type of the operation, which in this case can be either credit or debit
* the date and time of when the transaction was created

## Tasks
- [x] Model the table(s)
- [x] Define the swagger for the Create endpoint
- [x] Define the swagger for the List endpoint (method/protocol/request/response)
- [x] Define a simple mechanism for authentication(method/protocol/request/response)
- [x] Define the infra resources to the first version/release
  - [x] Storage Layer
  - [x] Entry point for the APIs (API gateway) 
  - [x] Communication pattern (channels for distributed integration)
- [x] Define the workflow to notify other consumers
