### ISSUE TITLE
POST - transactions - endpoint to create transactions

### ISSUE THREAD

**Issue by mauriciozanettisalomao** [mauriciozanettisalomao/go-transaction-service#2]
## Description
According to the following design, create a new endpoint to save transactions in the system
* Data Model Diagram
  * https://github.com/mauriciozanettisalomao/go-transaction-service/issues/1#issuecomment-1902453601
* Swagger (operationId: createTransaction)
  * https://github.com/mauriciozanettisalomao/go-transaction-service/issues/1#issuecomment-1902463955 
* Stack
  * https://github.com/mauriciozanettisalomao/go-transaction-service/issues/1#issuecomment-1902600485

## Tasks
- [x] Provision infra (data layer, api gateway, etc) using IaC
- [x] Implement the business logic to save a transaction based on the swagger described above
  - [x] Include an endpoint to create a user (model describes the user entity)
  - [x] In the `createTransaction` flow, validate if the type of operation is either credit or debit
  - [x] In the `createTransaction` flow, validate if the idempontency header was sent, if so, check if there is the same record into the DB
  - [x] In the `createTransaction` flow, check if the amount is more than ZERO
- [x] Include unit tests
- [x] Protect the API using an API key as the authentication mechanism
